language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO=1.7.8 MIGRATE='./manage.py migrate --settings=testproject.settings'
  - DJANGO=1.8.2 MIGRATE='./manage.py migrate --settings=testproject.settings'

branches:
  only:
    - master
    - develop

install:
  - pip install -q Django==$DJANGO
  - pip install -r testproject/requirements.txt
  - python setup.py -q install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd testproject && $MIGRATE && ./manage.py test --settings=testproject.settings
